name: Debug me

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        # Need to reference this here for now, otherwise it's going to be removed.
        run: echo Hello, world ${{ secrets.ACTIONS_WORKFLOW_DEBUG }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
