name: Debug me

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [debug,ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: 'vscode://cschleiden.vscode-github-actions?url=test'
        run: echo "vscode://cschleiden.vscode-github-actions?url=test"
      - id: fruit
        run: echo "::set-output name=action_fruit::strawberry"
      - run: echo "another step"      
      - run: echo "hello world"
      - run: echo "again"
