name: Debug me

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [debug,ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: 'vscode://cschleiden.vscode-github-actions?url=test'
        run: echo "vscode://cschleiden.vscode-github-actions?url=test"
      - run: echo "another step"
      - run: exit 1
      - run: echo "hello world"
      - run: echo "again"
