name: Debug me

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [debug,ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - id: fruit
        run: echo "::set-output name=action_fruit::strawberry"
      - run: echo "another step"      
      - run: exit 1
      - run: echo "hello world"
        if: always()
      - run: echo "again"
        if: always()
